Repository 8TB-Team/8TB-Chaek, pull requests merged in 2025-09, with the labels that each got.

#36 Feat/reservation init
  src/main/java/com/example/chackchack/domain/reservation/entity/Reservation.java
  src/main/java/com/example/chackchack/domain/reservation/entity/ReservationStatus.java
  src/main/java/com/example/chackchack/domain/reservation/exception/InvalidReservationException.java
  src/main/java/com/example/chackchack/domain/reservation/exception/ReservationErrorCode.java
  src/main/java/com/example/chackchack/domain/reservation/repository/ReservationRepository.java
  tash pop
Labels: ⭐️ Feature

#52 Feat/rental
  src/main/java/com/example/chackchack/domain/bookItem/controller/BookItemController.java
  src/main/java/com/example/chackchack/domain/bookItem/dto/request/BookItemRequest.java
  src/main/java/com/example/chackchack/domain/bookItem/dto/response/BookItemResponse.java
  src/main/java/com/example/chackchack/domain/bookItem/entity/BookItem.java
  src/main/java/com/example/chackchack/domain/bookItem/mapper/BookItemMapper.java
  src/main/java/com/example/chackchack/domain/bookItem/repository/BookItemRepository.java
  src/main/java/com/example/chackchack/domain/rental/controller/RentalController.java
  src/main/java/com/example/chackchack/domain/rental/dto/request/RentalCreateRequest.java
  src/main/java/com/example/chackchack/domain/rental/dto/request/RentalUpdateRequest.java
  src/main/java/com/example/chackchack/domain/rental/dto/response/RentalCreateResponse.java
  src/main/java/com/example/chackchack/domain/rental/dto/response/RentalPageResponse.java
  src/main/java/com/example/chackchack/domain/rental/dto/response/RentalResponse.java
  src/main/java/com/example/chackchack/domain/rental/dto/response/RentalUpdateResponse.java
  src/main/java/com/example/chackchack/domain/rental/entity/Rental.java
  src/main/java/com/example/chackchack/domain/rental/enums/RentalStatus.java
  src/main/java/com/example/chackchack/domain/rental/exception/RentalErrorCode.java
  src/main/java/com/example/chackchack/domain/rental/repository/RentalRepository.java
  src/main/java/com/example/chackchack/domain/rental/service/RentalInternalService.java
Labels: ⭐️ Feature

#55 Feat/rental
  src/main/java/com/example/chackchack/domain/rental/controller/RentalController.java
  src/main/java/com/example/chackchack/domain/rental/repository/RentalRepository.java
  src/main/java/com/example/chackchack/domain/rental/service/RentalInternalService.java
Labels: ⭐️ Feature

#57 refactor: rental 도서 예약 가능 확인 성능 개선
  src/main/java/com/example/chackchack/domain/rental/repository/RentalRepository.java
  src/main/java/com/example/chackchack/domain/rental/service/RentalExternalServiceImpl.java
Labels: ♻️ Refactoring

#62 Feat/review service test
  src/main/java/com/example/chackchack/domain/review/entity/Review.java
  src/test/java/com/example/chackchack/domain/review/service/ReviewInternalServiceTest.java
Labels: 🧪Test

#64 hotfix: 403 이슈 해결
  src/main/java/com/example/chackchack/common/security/SecurityConfig.java
  src/main/java/com/example/chackchack/domain/auth/controller/AuthController.java
Labels: 😡 Bug Fix

#66 Refactor/builder
  src/main/java/com/example/chackchack/domain/book/controller/BookController.java
  src/main/java/com/example/chackchack/domain/book/dto/response/BookResponse.java
  src/main/java/com/example/chackchack/domain/book/entity/Book.java
  src/main/java/com/example/chackchack/domain/book/exception/BookErrorCode.java
  src/main/java/com/example/chackchack/domain/book/service/BookExternalServiceImpl.java
  src/main/java/com/example/chackchack/domain/book/service/BookInternalService.java
Labels: ♻️ Refactoring

#74 feat: ReservationRepository 작성
  src/main/java/com/example/chackchack/domain/reservation/repository/ReservationRepository.java
Labels: ⭐️ Feature

#77 Feat/search
  src/main/java/com/example/chackchack/domain/book/repository/BookRepository.java
  src/main/java/com/example/chackchack/domain/book/service/BookInternalService.java
  src/main/java/com/example/chackchack/domain/search/controller/SearchKeywordController.java
  src/main/java/com/example/chackchack/domain/search/entity/SearchKeyword.java
  src/main/java/com/example/chackchack/domain/search/repository/SearchKeywordRepository.java
  src/main/java/com/example/chackchack/domain/search/service/SearchKeywordExternalService.java
  src/main/java/com/example/chackchack/domain/search/service/SearchKeywordExternalServiceImpl.java
  src/main/java/com/example/chackchack/domain/search/service/SearchKeywordInternalService.java
Labels: ⭐️ Feature
