Repository 8TB-Team/8TB-Chaek, pull requests merged in 2025-10, with the labels that each got.

#88 Feat/flash event
  build.gradle
  src/main/java/com/example/chackchack/domain/flashEvent/controller/FlashEventController.java
  src/main/java/com/example/chackchack/domain/flashEvent/dto/request/EventCreateRequest.java
  src/main/java/com/example/chackchack/domain/flashEvent/dto/response/EventCreateResponse.java
  src/main/java/com/example/chackchack/domain/flashEvent/entity/EventMap.java
  src/main/java/com/example/chackchack/domain/flashEvent/entity/EventUserMap.java
  src/main/java/com/example/chackchack/domain/flashEvent/enums/EventStatus.java
  src/main/java/com/example/chackchack/domain/flashEvent/exception/EventErrorCode.java
  src/main/java/com/example/chackchack/domain/flashEvent/exception/EventException.java
  src/main/java/com/example/chackchack/domain/flashEvent/repository/EventMapRepository.java
  src/main/java/com/example/chackchack/domain/flashEvent/repository/EventUserMapRepository.java
  src/main/java/com/example/chackchack/domain/flashEvent/service/FlashEventService.java
  src/test/java/com/example/chackchack/domain/flashEvent/service/FlashEventServiceTest.java
  src/test/resources/application.yml
Labels: ⭐️ Feature, 🧪Test

#89 Feat/reservation index
  src/main/java/com/example/chackchack/domain/reservation/entity/Reservation.java
Labels: ⭐️ Feature

#91 refactor/BookInterceptor
  src/main/java/com/example/chackchack/domain/book/controller/BookController.java
  src/main/java/com/example/chackchack/domain/book/interceptor/BookInterceptor.java
  src/main/java/com/example/chackchack/domain/book/interceptor/WebConfig.java
  src/main/java/com/example/chackchack/domain/book/service/BookInternalService.java
Labels: ♻️ Refactoring

#95 refactor: rental 반납 rentalId-> serial Number
  src/main/java/com/example/chackchack/domain/rental/controller/RentalController.java
  src/main/java/com/example/chackchack/domain/rental/dto/request/RentalUpdateRequest.java
  src/main/java/com/example/chackchack/domain/rental/exception/RentalErrorCode.java
  src/main/java/com/example/chackchack/domain/rental/repository/RentalRepository.java
  src/main/java/com/example/chackchack/domain/rental/service/RentalInternalService.java
Labels: ♻️ Refactoring
